// flow-typed signature: b5031cf6b62656df8849bf31df90ef7e
// flow-typed version: <<STUB>>/express-nunjucks_v^1.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-nunjucks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-nunjucks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-nunjucks/index' {
  declare module.exports: $Exports<'express-nunjucks'>;
}
declare module 'express-nunjucks/index.js' {
  declare module.exports: $Exports<'express-nunjucks'>;
}
