// flow-typed signature: 48f6ad1f2c99b0b0de2e08102d9fbe9b
// flow-typed version: <<STUB>>/human-readable-ids_v^1.0.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'human-readable-ids'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'human-readable-ids' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'human-readable-ids/assets/adjectives' {
  declare module.exports: any;
}

declare module 'human-readable-ids/assets/animals' {
  declare module.exports: any;
}

declare module 'human-readable-ids/lists' {
  declare module.exports: any;
}

declare module 'human-readable-ids/src/generate-lists' {
  declare module.exports: any;
}

declare module 'human-readable-ids/src/tpl' {
  declare module.exports: any;
}

declare module 'human-readable-ids/tests/run-in-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'human-readable-ids/assets/adjectives.js' {
  declare module.exports: $Exports<'human-readable-ids/assets/adjectives'>;
}
declare module 'human-readable-ids/assets/animals.js' {
  declare module.exports: $Exports<'human-readable-ids/assets/animals'>;
}
declare module 'human-readable-ids/index' {
  declare module.exports: $Exports<'human-readable-ids'>;
}
declare module 'human-readable-ids/index.js' {
  declare module.exports: $Exports<'human-readable-ids'>;
}
declare module 'human-readable-ids/lists.js' {
  declare module.exports: $Exports<'human-readable-ids/lists'>;
}
declare module 'human-readable-ids/src/generate-lists.js' {
  declare module.exports: $Exports<'human-readable-ids/src/generate-lists'>;
}
declare module 'human-readable-ids/src/tpl.js' {
  declare module.exports: $Exports<'human-readable-ids/src/tpl'>;
}
declare module 'human-readable-ids/tests/run-in-node.js' {
  declare module.exports: $Exports<'human-readable-ids/tests/run-in-node'>;
}
