// flow-typed signature: 982f4960ed26a3c585653b3b40278d5c
// flow-typed version: <<STUB>>/nodejs-dashboard_v^0.1.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodejs-dashboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodejs-dashboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodejs-dashboard/bin/nodejs-dashboard' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/config' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/dashboard-agent' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/dashboard' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/cpu-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/eventloop-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/memory-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/stream-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/app/index' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/dashboard-agent.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodejs-dashboard/bin/nodejs-dashboard.js' {
  declare module.exports: $Exports<'nodejs-dashboard/bin/nodejs-dashboard'>;
}
declare module 'nodejs-dashboard/index' {
  declare module.exports: $Exports<'nodejs-dashboard'>;
}
declare module 'nodejs-dashboard/index.js' {
  declare module.exports: $Exports<'nodejs-dashboard'>;
}
declare module 'nodejs-dashboard/lib/config.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/config'>;
}
declare module 'nodejs-dashboard/lib/dashboard-agent.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/dashboard-agent'>;
}
declare module 'nodejs-dashboard/lib/dashboard.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/dashboard'>;
}
declare module 'nodejs-dashboard/lib/views/cpu-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/cpu-view'>;
}
declare module 'nodejs-dashboard/lib/views/eventloop-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/eventloop-view'>;
}
declare module 'nodejs-dashboard/lib/views/memory-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/memory-view'>;
}
declare module 'nodejs-dashboard/lib/views/stream-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/stream-view'>;
}
declare module 'nodejs-dashboard/test/app/index.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/app/index'>;
}
declare module 'nodejs-dashboard/test/lib/dashboard-agent.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/dashboard-agent.spec'>;
}
