// flow-typed signature: ea7ca2e770f1b62be9ff6840bca63ebb
// flow-typed version: <<STUB>>/optimize-js-plugin_v^0.0.4/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimize-js-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimize-js-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optimize-js-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optimize-js-plugin/lib/index.js' {
  declare module.exports: $Exports<'optimize-js-plugin/lib/index'>;
}
