// flow-typed signature: 97cbd609ef83e148c5497da6d5fdac48
// flow-typed version: <<STUB>>/phaser-debug_v^1.1.8/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phaser-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'phaser-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phaser-debug/dist/phaser-debug' {
  declare module.exports: any;
}

declare module 'phaser-debug/gulpfile' {
  declare module.exports: any;
}

declare module 'phaser-debug/src/index' {
  declare module.exports: any;
}

declare module 'phaser-debug/src/panels/Panel' {
  declare module.exports: any;
}

declare module 'phaser-debug/src/panels/Performance' {
  declare module.exports: any;
}

declare module 'phaser-debug/src/panels/Scene' {
  declare module.exports: any;
}

declare module 'phaser-debug/src/util/Graph' {
  declare module.exports: any;
}

declare module 'phaser-debug/src/util/ui' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phaser-debug/dist/phaser-debug.js' {
  declare module.exports: $Exports<'phaser-debug/dist/phaser-debug'>;
}
declare module 'phaser-debug/gulpfile.js' {
  declare module.exports: $Exports<'phaser-debug/gulpfile'>;
}
declare module 'phaser-debug/src/index.js' {
  declare module.exports: $Exports<'phaser-debug/src/index'>;
}
declare module 'phaser-debug/src/panels/Panel.js' {
  declare module.exports: $Exports<'phaser-debug/src/panels/Panel'>;
}
declare module 'phaser-debug/src/panels/Performance.js' {
  declare module.exports: $Exports<'phaser-debug/src/panels/Performance'>;
}
declare module 'phaser-debug/src/panels/Scene.js' {
  declare module.exports: $Exports<'phaser-debug/src/panels/Scene'>;
}
declare module 'phaser-debug/src/util/Graph.js' {
  declare module.exports: $Exports<'phaser-debug/src/util/Graph'>;
}
declare module 'phaser-debug/src/util/ui.js' {
  declare module.exports: $Exports<'phaser-debug/src/util/ui'>;
}
