// flow-typed signature: 729410e7f2c0d74a3caa58bd050e67c4
// flow-typed version: <<STUB>>/store_v^1.3.20/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'store/build' {
  declare module.exports: any;
}

declare module 'store/json' {
  declare module.exports: any;
}

declare module 'store/scripts/3-run-saucelabs-tests' {
  declare module.exports: any;
}

declare module 'store/scripts/saucelabs-platformSets' {
  declare module.exports: any;
}

declare module 'store/store' {
  declare module.exports: any;
}

declare module 'store/store.min' {
  declare module.exports: any;
}

declare module 'store/store+json2.min' {
  declare module.exports: any;
}

declare module 'store/tests/browser-test-runner' {
  declare module.exports: any;
}

declare module 'store/tests/node-test-runner' {
  declare module.exports: any;
}

declare module 'store/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'store/build.js' {
  declare module.exports: $Exports<'store/build'>;
}
declare module 'store/json.js' {
  declare module.exports: $Exports<'store/json'>;
}
declare module 'store/scripts/3-run-saucelabs-tests.js' {
  declare module.exports: $Exports<'store/scripts/3-run-saucelabs-tests'>;
}
declare module 'store/scripts/saucelabs-platformSets.js' {
  declare module.exports: $Exports<'store/scripts/saucelabs-platformSets'>;
}
declare module 'store/store.js' {
  declare module.exports: $Exports<'store/store'>;
}
declare module 'store/store.min.js' {
  declare module.exports: $Exports<'store/store.min'>;
}
declare module 'store/store+json2.min.js' {
  declare module.exports: $Exports<'store/store+json2.min'>;
}
declare module 'store/tests/browser-test-runner.js' {
  declare module.exports: $Exports<'store/tests/browser-test-runner'>;
}
declare module 'store/tests/node-test-runner.js' {
  declare module.exports: $Exports<'store/tests/node-test-runner'>;
}
declare module 'store/tests/tests.js' {
  declare module.exports: $Exports<'store/tests/tests'>;
}
