// flow-typed signature: 969bffef1ba79e4169405efd268aca9a
// flow-typed version: <<STUB>>/webpack-obfuscator_v^0.7.3/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-obfuscator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-obfuscator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-obfuscator/test/config/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-obfuscator/test/input/index' {
  declare module.exports: any;
}

declare module 'webpack-obfuscator/test/input/index1' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-obfuscator/index' {
  declare module.exports: $Exports<'webpack-obfuscator'>;
}
declare module 'webpack-obfuscator/index.js' {
  declare module.exports: $Exports<'webpack-obfuscator'>;
}
declare module 'webpack-obfuscator/test/config/webpack.config.js' {
  declare module.exports: $Exports<'webpack-obfuscator/test/config/webpack.config'>;
}
declare module 'webpack-obfuscator/test/input/index.js' {
  declare module.exports: $Exports<'webpack-obfuscator/test/input/index'>;
}
declare module 'webpack-obfuscator/test/input/index1.js' {
  declare module.exports: $Exports<'webpack-obfuscator/test/input/index1'>;
}
